




















































































































































































































































































































































































































































































































  6%|█████████████▏                                                                                                                                                                                                    | 30692/490900 [23:48<3:15:17, 39.28it/s]Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "C:\Users\janwe\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\janwe\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\janwe\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_run.py", line 170, in check_status
    status_response = self._interface.communicate_stop_status()
  File "C:\Users\janwe\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\interface\interface.py", line 127, in communicate_stop_status
    resp = self._communicate_stop_status(status)
  File "C:\Users\janwe\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 395, in _communicate_stop_status
    resp = self._communicate(req, local=True)
  File "C:\Users\janwe\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\janwe\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
  6%|█████████████▏                                                                                                                                                                                                    | 30709/490900 [23:50<5:57:24, 21.46it/s]
Traceback (most recent call last):
  File "c:\Users\janwe\OneDrive\Desktop\Master_Thesis\Other projects\moral_rl\moral\ppo_train.py", line 69, in <module>
    wandb.log({'Obj_' + str(i): objective_logs[:, i].mean()})
  File "C:\Users\janwe\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_run.py", line 256, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\janwe\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_run.py", line 222, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\janwe\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_run.py", line 1548, in log
    self._log(data=data, step=step, commit=commit)
  File "C:\Users\janwe\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_run.py", line 1339, in _log
    self._partial_history_callback(data, step, commit)
  File "C:\Users\janwe\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_run.py", line 1228, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "C:\Users\janwe\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\interface\interface.py", line 553, in publish_partial_history
    self._publish_partial_history(partial_history)
  File "C:\Users\janwe\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 62, in _publish_partial_history
    self._publish(rec)
  File "C:\Users\janwe\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 49, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown